import Link from 'next/link'
import { Navbar } from '@/components/navbar'
import { Sidebar } from '@/components/sidebar'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Image, Video, History, TrendingUp, Shield, ArrowRight } from 'lucide-react'

export default function DashboardPage() {
  return (
    <div className="min-h-screen">
      <Navbar />
      
      <div className="flex">
        <Sidebar />
        
        <main className="ml-64 flex-1 p-8">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-foreground">Welcome to DeepGuard</h1>
            <p className="mt-2 text-muted-foreground">
              Your AI-powered deepfake detection dashboard
            </p>
          </div>

          {/* Quick Actions */}
          <div className="mb-8 grid gap-6 md:grid-cols-2">
            <Card className="group transition-all hover:border-cyan-500/50">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="rounded-lg bg-cyan-500/10 p-3">
                    <Image className="h-6 w-6 text-cyan-500" />
                  </div>
                  <ArrowRight className="h-5 w-5 text-muted-foreground transition-transform group-hover:translate-x-1" />
                </div>
                <CardTitle className="mt-4">Analyze Image</CardTitle>
                <CardDescription>
                  Upload an image to detect if it has been manipulated or generated by AI
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Link href="/analyze/image">
                  <Button className="w-full bg-cyan-600 hover:bg-cyan-700 text-white">
                    Start Image Analysis
                  </Button>
                </Link>
              </CardContent>
            </Card>

            <Card className="group transition-all hover:border-cyan-500/50">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="rounded-lg bg-purple-500/10 p-3">
                    <Video className="h-6 w-6 text-purple-500" />
                  </div>
                  <ArrowRight className="h-5 w-5 text-muted-foreground transition-transform group-hover:translate-x-1" />
                </div>
                <CardTitle className="mt-4">Analyze Video</CardTitle>
                <CardDescription>
                  Upload a video to detect deepfake manipulations using temporal analysis
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Link href="/analyze/video">
                  <Button variant="outline" className="w-full">
                    Start Video Analysis
                  </Button>
                </Link>
              </CardContent>
            </Card>
          </div>

          {/* Stats Overview */}
          <div className="mb-8 grid gap-4 md:grid-cols-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  Total Scans
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-foreground">24</div>
                <p className="text-xs text-muted-foreground">+3 this week</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  Images Analyzed
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-foreground">18</div>
                <p className="text-xs text-muted-foreground">Last: 2 hours ago</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  Videos Analyzed
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-foreground">6</div>
                <p className="text-xs text-muted-foreground">Last: 1 day ago</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  Deepfakes Found
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-red-500">7</div>
                <p className="text-xs text-muted-foreground">29% detection rate</p>
              </CardContent>
            </Card>
          </div>

          {/* Recent Activity */}
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Recent Activity</CardTitle>
                  <CardDescription>Your latest analysis results</CardDescription>
                </div>
                <Link href="/history">
                  <Button variant="ghost" size="sm">
                    View All
                    <History className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {[
                  { type: 'Image', result: 'Real', confidence: 0.94, time: '2 hours ago' },
                  { type: 'Video', result: 'Fake', confidence: 0.87, time: '5 hours ago' },
                  { type: 'Image', result: 'Fake', confidence: 0.92, time: '1 day ago' },
                ].map((item, index) => (
                  <div
                    key={index}
                    className="flex items-center justify-between rounded-lg border border-border p-4"
                  >
                    <div className="flex items-center gap-4">
                      <div className={`rounded-lg p-2 ${item.type === 'Image' ? 'bg-cyan-500/10' : 'bg-purple-500/10'}`}>
                        {item.type === 'Image' ? (
                          <Image className="h-4 w-4 text-cyan-500" />
                        ) : (
                          <Video className="h-4 w-4 text-purple-500" />
                        )}
                      </div>
                      <div>
                        <p className="font-medium text-foreground">{item.type} Analysis</p>
                        <p className="text-sm text-muted-foreground">{item.time}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      <div className="text-right">
                        <p className={`font-medium ${item.result === 'Real' ? 'text-emerald-500' : 'text-red-500'}`}>
                          {item.result}
                        </p>
                        <p className="text-sm text-muted-foreground">
                          {(item.confidence * 100).toFixed(0)}% confidence
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </main>
      </div>
    </div>
  )
}
